# Generated by Django 2.2.2 on 2019-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Organization', models.CharField(max_length=120)),
                ('Name_of_Event', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=500)),
                ('Date_time', models.DateField(default='2019-06-25', null=True)),
                ('Registration_Link', models.URLField()),
                ('Description', models.TextField(max_length=10000)),
                ('lat', models.DecimalField(decimal_places=6, default=32.076179, max_digits=20, null=True)),
                ('lon', models.DecimalField(decimal_places=6, default=-81.088379, max_digits=20, null=True)),
                ('Authorization_token', models.CharField(max_length=20)),
            ],
        ),
    ]
