# Generated by Django 2.2.2 on 2019-06-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmarker',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='addmarker',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='addmarker',
            old_name='Name_of_Organization',
            new_name='users_name',
        ),
        migrations.RemoveField(
            model_name='addmarker',
            name='Authorization_token',
        ),
        migrations.RemoveField(
            model_name='addmarker',
            name='Date_time',
        ),
        migrations.RemoveField(
            model_name='addmarker',
            name='Name_of_Event',
        ),
        migrations.RemoveField(
            model_name='addmarker',
            name='Registration_Link',
        ),
    ]
